### PR TITLE
竹→⺮, 𠂊→⺈, 乙→乚; adding "kvg:number" where needed; fixing errors

### PR DESCRIPTION
**Pull request by vitaliylag**
1. Changed 竹 to ⺮, 𠂊 to ⺈, 乙 to 乚 (where needed, see comments in commits)
2. Added "kvg:number" attribute where it is needed
3. Fixed errors in 乘尨、亭帯欄脩、壌壤嬢孃攘曩禳穣穰譲讓醸釀驤
4. Converted README to README.md

### CODE REVIEW

**Comment by vitaliylag** [comment]
Can you see it again?

Sorry, I was not familiar with Git so didn't know what to do first time. It is now fixed.

**Comment by vitaliylag** [comment]
Did you read this message? It is not the same pull request that had errors. If you don't have a time to see it write you see it later or merge it without checking.

**Comment by weirdalsuperfan** [comment]
Does this build on the other currently open pull requests?

**Comment by benkasminbullock** [comment]
These changes seem to have been done on another pull request. If it's not OK yet, please reopen this.

**Pull request closed without merging**
