### PR TITLE
kvg:element="冫": add  kvg:original="氷"

### PR DESCRIPTION
**Pull request by leoboiko**
I only added kvg:original="氷" to kanji that several sources agreed that 冫 was representing 氷.  The list of kanji changed is:

冫冬冰冱冴况冶冷冽凄凅凉凋凌凍凛凜凝寒憑柊疼苳螽馮鮗鼕冷

I skipped kanji which have a visual 冫 but it doesn’t represent 氷, like 次 or 弱 (or when there were doubts).  These are:

佻侭兆冲决准凖函匀咨唹均塁姚姿嫋嫋尽嵶嵶弱弱恣懿挑搦搦摂於晁桃楽檪次涵淤渋渋溺溺率瓷疂盗眺窕粢終茨蒻蒻蔆薬蟀誂諮資跳軣逃鈞銚閼韵鯲鰯鰯鶸鶸

Sources consulted were the four dictionaries available via http://namakajiri.net/kanjigen .

### CODE REVIEW

**Comment by ospalh** [comment]
>  visual 冫 but it doesn’t represent 氷, like 次

I just learned something new again today. :smile:  [Looks](http://www.kanjinetworks.com/eng/kanji-dictionary/online-kanji-etymology-dictionary.cfm?kanji_id=SAR05) like that was a 二. Do you want to add `kvg:original="二"`?

The `kvg:original="氷"` look good so far.

**Comment by leoboiko** [comment]
Yeah, at first I just sed 氷 into every , it was a massacre… Sure, I can add 二 to characters based on 次 and  匀, do you want those in the same pull request?

Another 冫 thing I found looking at this:
蔆, 0x08506, is an alternate form of 菱 RYŌ/hishi "water caltrop" (Trapa japonica).  The alternate form adds the sanzui, three-drops water component 氵 .

In KanjiVG, 08506.svg has a group listing 凌 as a component of the alternate form 蔆.  凌 looks a lot like the bottom of 蔆, but instead of 氵 it has the two-drops component, 冫 (which means that, in current KanjiVG, two-drop 冫 is an "invisible" component of 蔆).

Two-drop usually represents "ice" 氷.  凌 RYŌ/shinogu in fact has the original meaning of "accumulated ice" (plus lots of borrowed meanings).  I don't think it's underlying 蔆 "water caltrop".  Rather, 蔆 must be just the usual 菱 with water 氵 added for emphasis.

**Comment by ospalh** [comment]
> (D2o you want those in the same pull request?

Sure, why not.

Then again, while i think it looks good, i guess i would like to hear a second opinion. @Gnurou? @eichhirn?

**Comment by leoboiko** [comment]
Some more changes added to pull request as discussed.  Please review the commits :)

I added ニ to 次, 匀 and their composites.  Some think 於 was a semantic ニ too, but some disagree, so I left it alone.

I think I shouldn't mess with 蔆 before you guys say what you think about its 冫 issue.

Regarding these kanjis with a four-dots simplification element:
疂塁 (from 疊壘)
摂 (from 攝)
渋 (from 澁)
軣 (from 轟)
I think it would make more sense to group things a bit differently than what's currently done.  For example, in 摂, the three-ears component 聶 could be the kvg:original of the entire right side of 摂 (攝), not just the top.  And then the left two-drops and the right two-drops could each have a kvg:original="耳".  Do you think it makes sense? Cf. branch fourdots in my repo: ae8d329927c140674e8fcd11393c922abf86e311

For reference, here are all the KanjiVG characters including 冫 two drops, grouped by visual elements:

冫冷寒凝均冴凄凋冬凍柊冶凌冷冱冰况冽凅凉凛憑疼苳螽馮鮗鼕凜終 (冫 is 氷)

次懿恣咨姿瓷盗粢茨諮資  (冫 is 二)

匀均鈞韵 (冫 is 二)

兆挑眺跳銚桃逃佻姚晁窕誂

鰯弱溺嫋嵶搦蒻鶸

於唹淤閼鯲 (origin of 冫 uncertain)

楽檪薬

准凖 (冫simplified from water 氵)
冲 (ibid.)
决 (ibid.)

尽侭 (original 盡; but it ins't clear whether four-dots is 火)

率蟀

函涵

**Comment by ospalh** [comment]
>>   (D)o you want those in the same pull request?
>
> Sure, why not.

Or perhaps in a new one after all.
I got no complaints from other people. That’s good enough for me.

**Pull request merged**
