### PR TITLE
add groups elements for 戸 and 立

### PR DESCRIPTION
**Pull request by vdheuvel**
Added groups for the bottom parts of 戸 and 立

### CODE REVIEW

**Comment by vdheuvel** [comment]
Is this something that is useful to the main fork? I might be making more edits like this one for my own project. If you think it is useful, I'll create more PRs in the future.

**Comment by Gnurou** [comment]
Sorry, we are not super reactive lately. >_< To be honest, we are missing the expertise of an active scholar who could confirm whether these corrections are accurate (in the academic sense) or not. I took a look at them and they make sense from a logical standpoint, but I don't know if for instance 立 is supposed to be split further.

**Comment by vdheuvel** [comment]
Hm it would be a shame if that would block improvements, but I'll leave that to you to decide.
Good point, I see there is 丷too, so I can group it further. I'm looking at it from a visual perspective though.

**Comment by vdheuvel** [comment]
I tried using harmonize-svg.py to validate my changes, but it gave me the same errors both before and after my edits. Errors were no stroke numbers group and no stroke paths group, though both exist. I suppose it's safe to ignore these?

**Comment by benkasminbullock** [comment]
I don't agree with this commit, if 立 is split into groups here it should be split everywhere consistently. I cannot really see the benefit of splitting this element. Similarly with the other thing, except that seems to be more useful in terms of splitting it into viable component parts.

**Comment by vdheuvel** [comment]
Thanks for looking into it, Ben. Consistency with all the other glyphs is a good argument, I didn't think of that. 
I'm not planning to go in that direction with my edits at this point, so I'll close this PR.

**Pull request closed without merging**
