### PR TITLE
Convert make-index script to Python

### PR DESCRIPTION
**Pull request by nix6839**
The repository's scripts now only include `.sh` and `.py`, and there's no longer a need to install additional dependency like `JSON::Create`.

### CODE REVIEW

**Comment by benkasminbullock** [comment]
Thank you for the pull request. What is the motivation for this change? The index file generated here is a means of supporting the website version of kanjivg at kanjivg.tagaini.net. So the only person who's going to run the make-index.pl or python equivalent script at the moment is the person making the website version of kanjivg. That's just me (Ben Bullock) at the moment. I suppose having this in Python might be easier for other people to run it, but nobody is doing that at the moment. Is there some other reason this needs to be in Python, like people wanting to run the index script themselves for some purpose and getting stuck on it being in Perl, and requiring a module installation?

**Comment by nix6839** [comment]
> Thank you for the pull request. What is the motivation for this change? The index file generated here is a means of supporting the website version of kanjivg at kanjivg.tagaini.net. So the only person who's going to run the make-index.pl or python equivalent script at the moment is the person making the website version of kanjivg. That's just me (Ben Bullock) at the moment. I suppose having this in Python might be easier for other people to run it, but nobody is doing that at the moment. Is there some other reason this needs to be in Python, like people wanting to run the index script themselves for some purpose and getting stuck on it being in Perl, and requiring a module installation?

Oh... I thought this file was used elsewhere as well. I'll go ahead and close the PR.

**Comment by benkasminbullock** [comment]
I don't think it's used elsewhere at the moment. Someone other than me might take over the maintenance of this repository in the future and want to keep the web version alive, so at that moment your Python script might be just what they want.

**Comment by nix6839** [comment]
Anyway, thanks for maintaining such a good project!

**Comment by benkasminbullock** [comment]
I decided to use this and delete the Perl file, but it can't be done now from github so I had to copy and paste it. I apologise but your contribution will not show up in the logs.

Thanks for the contribution.

**Pull request closed without merging**
