### PR TITLE
Added missing stroke numbers in Kaisho kanji

### PR DESCRIPTION
**Pull request by MissingRice**
Added the missing stroke numbers in the Kaisho kanji from #441. This was done with a script, however I did visually verify 51 number positions. Some kanji from #441 have already been fixed (see bottom list).

Here's a list showing all the verified kanji:

- 05dd2-Kaisho.svg 
- 05f4e-Kaisho.svg
- 06ade-Kaisho.svg
- 06b12-Kaisho.svg
- 07063-Kaisho.svg
- 07cfa-Kaisho.svg
- 07cfe-Kaisho.svg
- 07d00-Kaisho.svg
- 07d02-Kaisho.svg
- 07d04-Kaisho.svg
- 07d05-Kaisho.svg
- 07d0b-Kaisho.svg
- 07d0d-Kaisho.svg
- 07d10-Kaisho.svg
- 07d14-Kaisho.svg
- 07d15-Kaisho.svg
- 07d17-Kaisho.svg
- 07d18-Kaisho.svg
- 07d19-Kaisho.svg
- 07d1a-Kaisho.svg
- 07d1c-Kaisho.svg
- 07d21-Kaisho.svg
- 07d2c-Kaisho.svg
- 07d30-Kaisho.svg
- 07d32-Kaisho.svg
- 07d33-Kaisho.svg
- 07d35-Kaisho.svg
- 07d39-Kaisho.svg
- 07d3a-Kaisho.svg
- 07d3f-Kaisho.svg
- 07d43-Kaisho.svg
- 07d44-Kaisho.svg
- 07d45-Kaisho.svg
- 07d42-Kaisho.svg
- 07d46-Kaisho.svg
- 07d4b-Kaisho.svg
- 07d4c-Kaisho.svg
- 07d50-Kaisho.svg
- 07d56-Kaisho.svg
- 07d5e-Kaisho.svg
- 07d62-Kaisho.svg
- 07d63-Kaisho.svg
- 07d66-Kaisho.svg
- 07d68-Kaisho.svg
- 07d71-Kaisho.svg
- 07d72-Kaisho.svg
- 07d73-Kaisho.svg
- 07d75-Kaisho.svg
- 07d76-Kaisho.svg
- 07d61-Kaisho.svg
- 07d89-Kaisho.svg

The already fixed kanji from #441 are:

- 07de9-Kaisho.svg
- 07def-Kaisho.svg
- 07e2e-Kaisho.svg
- 07e39-Kaisho.svg
- 07e3e-Kaisho.svg
- 07e8c-Kaisho.svg
- 07e90-Kaisho.svg
- 081e0-Kaisho.svg

### CODE REVIEW

**Comment by MissingRice** [comment]
I also accidentally added a second commit ('Fixed group error in kanji 0622f-VtFstLeRiTenFst') which is unrelated sorry. This is my first time contributing on Github. I was going to make a second pr for it anyway, so it should safe to merge.

**Comment by benkasminbullock** [comment]
Thanks, these stroke numbers all appear to be correctly placed, and the group error is also a good catch. If you have a script which can accurately place stroke numbers, it might be worth running it on the existing stroke numbers and check if they are correctly placed as well. I'm fairly sure that would turn up quite a few errors in the data.

**Comment by benkasminbullock** [comment]
> I also accidentally added a second commit ('Fixed group error in kanji 0622f-VtFstLeRiTenFst') which is unrelated sorry. This is my first time contributing on Github. I was going to make a second pr for it anyway, so it should safe to merge.

I think you have to make a new branch for each change, otherwise github "conveniently" adds them to the current pull request.

**Comment by MissingRice** [comment]
Thank you for the guidance, I'll use branches next time :)

> If you have a script which can accurately place stroke numbers, it might be worth running it on the existing stroke numbers and check if they are correctly placed as well. I'm fairly sure that would turn up quite a few errors in the data.

I did run my script over the entire collection and I only found the errors in #441. It did miss 07e3e-KaishoVtLst.svg strangely, so I'll look into it and see if I can find any others not included in this PR.

**Comment by benkasminbullock** [comment]
> > If you have a script which can accurately place stroke numbers, it might be worth running it on the existing stroke numbers and check if they are correctly placed as well. I'm fairly sure that would turn up quite a few errors in the data.
> 
> I did run my script over the entire collection and I only found the errors in #441. It did miss 07e3e-KaishoVtLst.svg strangely, so I'll look into it and see if I can find any others not included in this PR.

I mean run it over the existing numbers and see if they are located in roughly the right place. A lot of them definitely aren't even close to where they should be due to brokenness, usually in the -Kaisho.svg files. Generally that is because the strokes are disordered though, so you couldn't fix it by moving the numbers, you would need to actually edit the files. You would also need to program in some sort of "approximately close" algorithm, I don't know how well that would work.

If you look at the repository's list of commits, you'll see that I'm working through the errors that I know about, gradually.

**Comment by MissingRice** [comment]
> I mean run it over the existing numbers and see if they are located in roughly the right place. A lot of them definitely aren't even close to where they should be due to brokenness, usually in the -Kaisho.svg files.

Sadly my script isn't that sophisticated. All it's doing is checking if there is the same number of path and text elements, and if not, extracting the element/s from the base kanji. There isn't any kind of distance checking or anything, just copy and paste.

> ME: It did miss 07e3e-KaishoVtLst.svg strangely, so I'll look into it and see if I can find any others not included in this PR.

I checked again and I think all of the kanji with missing stroke numbers, Kaisho or not, have been found. I worked out the 07e3e-KaishoVtLst.svg problem and it didn't change the results.

> Generally that is because the strokes are disordered though, so you couldn't fix it by moving the numbers, you would need to actually edit the files. You would also need to program in some sort of "approximately close" algorithm, I don't know how well that would work.

Yeah, I think an algorithm like that would be quite time consuming to write and give questionable results. That being said, I would be happy to maybe look at some number positions (I would help with stroke order too but I don't know enough about writing Japanese) and correcting them, as some of them are squished or overlapping. I know you said it wouldn't solve the problem, but at the very least the numbers would be in a better position for when the stroke order is changed. Is this something that could be done with normal vector editing software like Inkscape and some manual file editing, or with the kvg tool?

> If you look at the repository's list of commits, you'll see that I'm working through the errors that I know about, gradually.

Thank you for your continual work on this great kanji database!

**Comment by benkasminbullock** [comment]
On Sat, 2 Nov 2024 at 15:44, MissingRice ***@***.***> wrote:

> I mean run it over the existing numbers and see if they are located in
> roughly the right place. A lot of them definitely aren't even close to
> where they should be due to brokenness, usually in the -Kaisho.svg files.
>
> Sadly my script isn't that sophisticated. All it's doing is checking if
> there is the same number of path and text elements, and if not, extracting
> the element/s from the base kanji. There isn't any kind of distance
> checking or anything, just copy and paste.
>

Oh I see, that's a good idea.


> ME: It did miss 07e3e-KaishoVtLst.svg strangely, so I'll look into it and
> see if I can find any others not included in this PR.
>
> I checked again and I think all of the kanji with missing stroke numbers,
> Kaisho or not, have been found. I worked out the 07e3e-KaishoVtLst.svg
> problem and it didn't change the results.
>
> Generally that is because the strokes are disordered though, so you
> couldn't fix it by moving the numbers, you would need to actually edit the
> files. You would also need to program in some sort of "approximately close"
> algorithm, I don't know how well that would work.
>
> Yeah, I think an algorithm like that would be quite time consuming to
> write and give questionable results. That being said, I would be happy to
> maybe look at some number positions (I would help with stroke order too but
> I don't know enough about writing Japanese) and correcting them, as some of
> them are squished or overlapping. I know you said it wouldn't solve the
> problem, but at the very least the numbers would be in a better position
> for when the stroke order is changed. Is this something that could be done
> with normal vector editing software like Inkscape and some manual file
> editing, or with the kvg tool?
>

The original inputs were apparently made with Adobe Illustrator by a group
of university students. I currently don't have any way of editing the
graphics themselves. There are not really that many problems with the
graphics I think so it hasn't been such a big issue.

**Pull request merged**
