### PR TITLE
竹→⺮, 𠂊→⺈, 乙→乚; adding "kvg:number" where needed; fixing errors

### PR DESCRIPTION
**Pull request by vitaliylag**
1. Changed 竹 to ⺮, 𠂊 to ⺈, 乙 to 乚 (where needed, see comments in commits)
2. Added "kvg:number" attribute where it is needed
3. Fixed errors in 乘尨、亭帯欄脩、壌壤嬢孃攘曩禳穣穰譲讓醸釀驤
4. Converted README to README.md

### CODE REVIEW

**Comment by vitaliylag** [comment]
Actually I don't if I correctly fixed 欄. In old version there was "柬" element. Yes, 闌 do have "柬" element. But 欄 have "東" element.

So we visually have: 欄 → 䦨 → 東
But 䦨 character is not even included in Japanese fonts so we have to write 欄 → 闌 → 柬/東

So I don't know should we write 柬 or 東. What do you think? Should I restore 柬? If I restore there will be bug with 日 because that bug was there before. I need to think how to fix that bug (may be you can help me with it). Or maybe we just need write 欄 → 闌 → 柬 → 東 so big will be fixed very easy. I want to hear your opinion.

**Comment by ospalh** [comment]
I’ll have a look at this.

**Comment by vitaliylag** [comment]
OK, but if you will not be able to see the PR a long time please merge it without checking.

**Comment by ospalh** [comment]
So i started to look at it.
And it’s a bit odd.
Where did the commit e765f05c7fa8bd1e50810e1647b2c68ed938484d come from?
It looks like 6afbf54ba798325e97a08055bae63edc0ab8651e, but with another hash. What?
Dto. 2afb794586634e4243769476c40503932ff3592c, which should be ecf9eb04a72c2d1f6085459610e50d6da4a846f8
Could you please start with an up to date kanjivg/master and only add your own commits to that?

**Comment by vitaliylag** [comment]
Actually I not familiar with Git. How do I do that?

I entered "rebase" to change my commit comments, and everything was good but after pushing to GitHub those 3 commits changed its photos :( How can I fix it? There is no any changes in those 3 commits. I thought you can just click "merge" and GitHub automatically do something.

**Comment by vitaliylag** [comment]
Should I create commits (or one commit with all changes) from the beginning? Or is there a way to fix it without it?

**Comment by vitaliylag** [comment]
I think I resolved the problem. I just had to create new branch from last master commit and add my 9 commits using "rebase" and "pick".

See https://github.com/KanjiVG/kanjivg/pull/164

**Pull request closed without merging**
